From https://github.com/erlang/otp/pull/46#issuecomment-21719585
"Since b29ecbd (OTP-10418, R15B03) Erlang does not compile anymore with
old versions of GCC that do not have atomic ops builtins on platforms
where there is no native ethread implementation (e.g. ARM): (...)

Please note however that I will be merging this branch as well,
which will mean that you have to explicitly tell configure that
you intend to use the fallback atomic operations though
--disable-native-ethr-impls or --disable-smp-require-native-atomics."

Translated: On NetBSD-5.1 (with gcc-4.1.3) the erlang package
didn't compile because of

>  ../include/internal/gcc/ethr_membar.h:49:4: error:
>	#error "No __sync_val_compare_and_swap"

Adding the abovementioned option --disable-native-ethr-impls make the
Erlang runtime system use the original (now fallback) code. This should
maybe be an pkg option, but for now this has to do.